# Site settings
title: "CCNA学習センター"
email: s3020809@surugadai.ac.jp
description: "This is a learning website for CCNA (Cisco Certified Network Associate)."
baseurl: "/Home"
url: ""

color_text:  "#fff"
color_theme:  "#FF7F24"

language:  "jp"
cors: ["/Home/search.json"]


# Build settings
markdown: kramdown
permalink: /:title/


# Plugins
plugins_dir:
  - jekyll-admin
future: true

collections:
  posts:
    output: true
    permalink: /posts/:title/


